image:
  repository: mazcot4devops/ml-app
  tag: latest

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

iam:
  roles:
  - name: ml-app-role
    policies:
    - "AmazonS3FullAccess"
    - "AmazonSQSFullAccess"
