apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yami
- deployment.yami
- service.yami
namespace: mi
images:
- name: mi-image
  newName: mazcot4devops/mi-app
  newTag: latest
