apiVersion: v1
kind: Service
metadata:
  name: mi-app-service
  namespace: mi
spec:
  selector:
    app: mi-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: {? {.Values.service.type: ''} : ''}
