apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-app-deployment
  namespace: ml
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-app
  template:
    metadata:
      labels:
        app: ml-app
    spec:
      containers:
      - name: ml-app
        image: ml-image
        ports:
        - containerPort: 8080
