apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: MI-app
  namespace: mi
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mi
  source:
    repoURL: 'https://github.com/mazcot-devops/MI'
    path: 'deployment'
    targetRevision: 'master'
  project: MI-app
  syncPolicy:
    automated: {}
